name: Server
main: me.spacekiller.main.Main
version: 1.0
author: Spacekiller
softdepend: [PermissionsEx]
commands:
   ?:
      description: help
   gamemode:
      description: gamemode
   gm:
      description: gamemode
   gui:
      description: gui
   h:
      description: help
   help:
      description: help
   joinmessage:
      description: set joinmessage
   nick:
      description: nick
   onlinezeit:
      description: shows onlinetime
   openinv:
      description: openinv
   openenderinv:
      description: openenderinv
   ram:
      description: shows ramusage
   ramcheck:
      description: shows ramusage detailed
   pl:
      description: denies pl
   plugin:
      description: denies plugin
   spacedragon:
      description: spacedragon
   spawn:
      description: spawntp
   team:
      description: team
   teamchat:
      description: teamchat
   test:
      description: test
   tp:
      description: tp
   tpaccept:
      description: tp
   tpdecline:
      description: tp
   tpdeny:
      description: tp
   whois:
      description: WhoIs