name: Server
main: me.spacekiller.main.Main
version: 1.0
author: Spacekiller
softdepend: [PermissionsEx]
commands:
   gamemode:
      description: gamemode
      aliases: [gm]
   help:
      description: help
      aliases: [h, ?]
   joinmessage:
      description: set joinmessage
   onlinezeit:
      description: shows onlinetime
   ram:
      description: shows ramusage
   ramcheck:
      description: shows ramusage detailed
   pl:
      description: denies pl
   plugin:
      description: denies plugin
   spacedragon:
      description: spacedragon
   whois:
      description: WhoIs